/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gloomyfish_jni_helloworld_HelloWorldJNI */

#ifndef _Included_com_gloomyfish_jni_helloworld_HelloWorldJNI
#define _Included_com_gloomyfish_jni_helloworld_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gloomyfish_jni_helloworld_HelloWorldJNI
 * Method:    helloJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gloomyfish_jni_helloworld_HelloWorldJNI_helloJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gloomyfish_jni_helloworld_HelloWorldJNI
 * Method:    helloJNI1
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gloomyfish_jni_helloworld_HelloWorldJNI_helloJNI1
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
